# Generated by Django 4.1.7 on 2023-03-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gi_videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=255)),
                ('releaseURL', models.CharField(max_length=255)),
                ('releaseDate', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('gamename', 'releaseURL', 'releaseDate')},
            },
        ),
        migrations.CreateModel(
            name='gi_videogame_release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('no_of_player', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('industry_rating', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.gi_videogame')),
            ],
        ),
    ]
